### ISSUE TITLE
RuntimeError in using sdk to load CMU-MOSEI data

### ISSUE THREAD

**Issue by jgkimi** [A2Zadeh/CMU-MultimodalSDK#222]
Hi. Thank you for sharing this code.

I've got a linking error when I load CMU-MOSEI data using the following code in python:

\>\>\> from mmsdk import mmdatasdk
\>\>\> cmumosei_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel,'cmumosei/')

The error is:
[2020-08-05 03:01:17.784] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedGloveVectors.csd does not exist
...
RuntimeError: URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedGloveVectors.csd does not exist
-------------------------------------------------------------------------------------------------------------------------------

MOSI is ok, but MOSEI is not.

I think this error is caused by the referred file name "CMU_MOSEI_TimestampedGloveVectors.csd" that does not exist in the path ("CMU_MOSEI_TimestampedWordVectors.csd" exists instead)

How could I do to load it?

Thank you.

**Comment by A2Zadeh** [comment]
Hi @jgkimi. Good catch! I fixed it. You can pull again and run your code ;)

**Comment by jgkimi** [comment]
Thank you for your fast response, but still not working because of the prefix "CMU_" that should also be removed. That was my mistake.

**Comment by jgkimi** [comment]
Thank you for your fast response, but still not working because of the prefix "CMU_" that should also be removed. That was my mistake.

**Comment by A2Zadeh** [comment]
@jgkimi Ah :). I will fix that now!
