### ISSUE TITLE
403 when accessing the raw data

### ISSUE THREAD

**Issue by alexunsworthfb** [A2Zadeh/CMU-MultimodalSDK#298]
Following the link http://immortal.multicomp.cs.cmu.edu/raw_datasets/ provides a 403, how do I go about getting access to this data?

**Comment by A2Zadeh** [comment]
@alexunsworthfb issue is solved now. Thanks for letting me know.

**Comment by aliJabra** [comment]
I still get 403 error for the   http://immortal.multicomp.cs.cmu.edu/* links...

**Comment by alexunsworthfb** [comment]
@A2Zadeh Thanks for looking at the issue, but it appears I still get 403 for the link I posted and the link @aliJabra posted.
